{"name": "Verify that user with ID 1 can be fetched successfully", "status": "broken", "statusDetails": {"message": "KeyError: 'api_base_url'", "trace": "config = {'allure': {'build_name': 'Local Test Run', 'build_order': '1', 'executor_name': 'Local Machine', 'report_name': 'API ...'}, 'default_headers': {'Accept': 'application/json', 'Content-Type': 'application/json'}, 'environment': 'Local', ...}\n\n    @allure.epic(\"User Management API\")\n    @allure.feature(\"GET /users/{id}\")\n    @allure.severity(allure.severity_level.CRITICAL)\n    @allure.title(\"Verify that user with ID 1 can be fetched successfully\")\n    def test_get_user_by_id(config):\n>       client = UserClient(config[\"api_base_url\"])\nE       KeyError: 'api_base_url'\n\ntests\\test_users_api.py:10: KeyError"}, "start": 1747038360314, "stop": 1747038360314, "uuid": "01f3f6c0-097f-413b-8dd5-ee3941f8efda", "historyId": "3ec43f87416c2bd041efeb5019e120b7", "testCaseId": "3ec43f87416c2bd041efeb5019e120b7", "fullName": "tests.test_users_api#test_get_user_by_id", "labels": [{"name": "severity", "value": "critical"}, {"name": "feature", "value": "GET /users/{id}"}, {"name": "epic", "value": "User Management API"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_users_api"}, {"name": "host", "value": "PLWRS-PF43AQAR"}, {"name": "thread", "value": "10020-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_users_api"}]}